CREATE DATABASE ACADEMY2
GO 
USE ACADEMY2
GO
CREATE TABLE LectureRooms(
    [Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Building] INT NOT NULL,
[Name] NVARCHAR(10) UNIQUE NOT NULL,
CONSTRAINT CB_LectureRooms CHECK  (Building BETWEEN 1 AND 5)
);
GO
CREATE TABLE Subjects(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Name] NVARCHAR(100) UNIQUE NOT NULL
);
GO
CREATE TABLE Teachers(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Name] NVARCHAR(max) NOT NULL,
[Surname] NVARCHAR(max) NOT NULL,
);
GO
CREATE TABLE Assistans(
 [Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[TeacherId] INT NULL,
CONSTRAINT KT_Assistans FOREIGN KEY (TeacherId) REFERENCES Teachers(Id)
);
GO
CREATE TABLE Dean(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[TeacherId] INT NULL,
CONSTRAINT KT_Dean FOREIGN KEY (TeacherId) REFERENCES Teachers(Id)
);
GO
CREATE TABLE Faculties(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Building] INT NOT NULL,
[Name] NVARCHAR(100) UNIQUE NOT NULL,
[DeanId] INT NOT NULL,
CONSTRAINT CB_Faculties CHECK (Building BETWEEN 1 AND 5),
CONSTRAINT KD_Facultie FOREIGN KEY (DeanId) REFERENCES Dean (Id)
);
GO
CREATE TABLE Heads(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[TeacherId] INT NOT NULL,
CONSTRAINT KT_Heads FOREIGN KEY (TeacherId) REFERENCES Teachers(Id)
);
GO
CREATE TABLE Departmens(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Building] INT NOT NULL,
[Name] NVARCHAR(100) UNIQUE NOT NULL,
[FucultyId] INT NOT NULL,
[HeadId] INT NOT NULL,
CONSTRAINT CB_Departmens CHECK (Building BETWEEN 1 AND 5),
CONSTRAINT KF_Departmens FOREIGN KEY(FucultyId) REFERENCES Faculties(Id),
CONSTRAINT KH_Departmens FOREIGN KEY (HeadId) REFERENCES Heads(Id),
);
GO
CREATE TABLE Groups(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Name] NVARCHAR(100) UNIQUE NOT NULL,
[Year] INT NOT NULL,
[DepartmensId] INT NOT NULL,
CONSTRAINT CY_Groups CHECK(Year BETWEEN 1 AND 5),
CONSTRAINT KD_Groups FOREIGN KEY (DepartmensId) REFERENCES Departmens(Id)
);
CREATE TABLE Curators(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[TeacherId] INT NOT NULL,
CONSTRAINT KT_Curators FOREIGN KEY (TeacherId) REFERENCES Teachers(Id)
);
GO
CREATE TABLE GroupCurators(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[CuratorId] INT NOT NULL,
[GroupId] INT NOT NULL,
CONSTRAINT FC_GroupCurators FOREIGN KEY (CuratorId) REFERENCES Curators(Id),
CONSTRAINT FG_GroupCurators FOREIGN KEY (GroupId) REFERENCES Groups(Id),
);
GO
CREATE TABLE Lectures(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[SubjectId] INT NOT NULL,
[TeacherId] INT NOT NULL,
CONSTRAINT FS_Lectures FOREIGN KEY (SubjectId) REFERENCES Subjects(Id),
CONSTRAINT FT_Lectures FOREIGN KEY (TeacherId) REFERENCES Teachers(Id)
)
GO
CREATE TABLE GroupsLectures(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[GroupId] INT NOT NULL,
[LectureId]  INT NOT NULL,
CONSTRAINT FG_GroupsLectures FOREIGN KEY (GroupId) REFERENCES Groups(Id),
CONSTRAINT FL_GroupsLectures FOREIGN KEY (LectureId) REFERENCES Lectures (Id)
);
GO
CREATE TABLE Schedules(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Class] INT NOT NULL,
[DayOfWeek] INT NOT NULL,
[Week] INT NOT NULL,
[LectureId] INT NOT NULL,
[LectureRoomId] INT NOT NULL,
CONSTRAINT CC_Schedules CHECK(Class BETWEEN 1 AND 8),
CONSTRAINT CD_Schedules CHECK (DayOfWeek BETWEEN 1 AND 7),
CONSTRAINT CW_Schedules CHECK(Week BETWEEN 1 AND 52),
CONSTRAINT KL_Schedules FOREIGN KEY (LectureId) REFERENCES Lectures(Id),
CONSTRAINT FKL_Schedules FOREIGN KEY (LectureRoomId) REFERENCES LectureRooms(Id)
); 
