CREATE DATABASE MusicCollection
GO 
USE MusicCollection
GO 
CREATE TABLE Record_Label (
  [Id]  INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  [Name] VARCHAR (50) UNIQUE NOT NULL,
);
GO 
CREATE TABLE Artist (
    [Id]  INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [Record_Label_Id] INT NOT NULL,
    [Name] VARCHAR (50) UNIQUE NOT NULL,
    [Surname] VARCHAR (50) UNIQUE NOT NULL,
  CONSTRAINT FK_Artist FOREIGN KEY (Record_Label_Id) REFERENCES Record_Label (Id),
);
GO
CREATE TABLE Album (
  [Id]  INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  [ArtistId] INT NOT NULL ,
  [Name]  VARCHAR (50) UNIQUE NOT NULL,
  [Year]  DATETIME NOT NULL,
  CONSTRAINT FK_artist_in_album FOREIGN KEY (ArtistId) REFERENCES Artist (Id),
);
GO
CREATE TABLE Song (
  [Id]  INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  [Album_id] INT NOT NULL,
  [Name]  VARCHAR (50) UNIQUE NOT NULL,
  [Duration] REAL NOT NULL,
  CONSTRAINT FK_album_in_song FOREIGN KEY (Album_id) REFERENCES Album (Id),
);
GO
CREATE TABLE Musical_Style(
  [Id]  INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  [Name]  VARCHAR (50) UNIQUE NOT NULL,
  [ArtistId] INT NOT NULL,
  [AlbumId] INT NOT NULL,
  CONSTRAINT FK_Musical_Style FOREIGN KEY (AlbumId) REFERENCES Album (Id),
  CONSTRAINT FK_Musical_Style_Artist FOREIGN KEY (ArtistId) REFERENCES Artist(Id),
); 
GO
CREATE TABLE Archive(
  [Id]  INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  [ArtistId] INT NOT NULL ,
  [Name]  VARCHAR (50) UNIQUE NOT NULL,
  [Year]  DATETIME NOT NULL,
  CONSTRAINT FK_Archive FOREIGN KEY (ArtistId) REFERENCES Artist (Id),
);