CREATE DATABASE Academy;
GO
USE Academy;
GO
CREATE TABLE Subjects (
    [Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL
);
GO
CREATE TABLE Teacher(
    [Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(MAX)  NOT NULL,
    [Salary] MONEY NOT NULL,
    [Surname] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT CS_Teacher CHECK (Salary>0),
);
GO
CREATE TABLE Lecture(
 [Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 [DayOfWeek] INT NOT NULL,
 [LectureRoom] NVARCHAR(MAX) NOT NULL,
 [SubjectId] INT NOT NULL,
 [TeacherId] INT NOT NULL,
 CONSTRAINT KDW_Lecture CHECK(DayOfWeek BETWEEN 1 AND 7),
 CONSTRAINT FKS_Lecture FOREIGN KEY (SubjectId) REFERENCES Subjects(Id),
 CONSTRAINT FKT_Lecture FOREIGN KEY (TeacherId) REFERENCES Teacher(Id),
);
GO
CREATE TABLE Facultiet(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL
);
GO
CREATE TABLE Department(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Financing] MONEY DEFAULT (0) NOT NULL,
[Name] NVARCHAR(100) UNIQUE NOT NULL,
[FacultyId] INT NOT NULL,
CONSTRAINT KF_Department CHECK (Financing>=0),
CONSTRAINT FKF_Department FOREIGN KEY (FacultyId) REFERENCES Facultiet(Id),
);
GO
CREATE TABLE Groups2(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Name] NVARCHAR(100) UNIQUE NOT NULL,
[Year] INT NOT NULL ,
[DepartmentId] INT NOT NULL,
CONSTRAINT FKD_Group FOREIGN KEY (DepartmentId)  REFERENCES Department(Id),
CONSTRAINT KY_Groups CHECK (Year BETWEEN 1 AND 5 ),
);
GO
CREATE TABLE GroupLecture(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[GroupId]  INT NOT NULL,
[LectureId] INT NOT NULL,
CONSTRAINT FKG_GroupLecture FOREIGN KEY (GroupId) REFERENCES Groups2(Id),
CONSTRAINT FKL_GroupLecture FOREIGN KEY(LectureId) REFERENCES Lecture(Id),
);
