CREATE DATABASE Shop;
GO 
USE Shop;
CREATE TABLE Employee(
[Id] INT  IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Name] VARCHAR(MAX) NOT NULL,
[Surname] VARCHAR(MAX) NOT NULL,
[Rang] INT NOT NULL,
CONSTRAINT CR_Employee CHECK(Rang BETWEEN 1 AND 5)
);
GO
CREATE TABLE Manager(
[Id] INT  IDENTITY(1,1) PRIMARY KEY NOT NULL,
[EmployeeId] INT NOT NULL,
CONSTRAINT FE_Manager FOREIGN KEY (EmployeeId) REFERENCES Employee(Id)
);
GO
CREATE TABLE Sellers(
[Id] INT  IDENTITY(1,1) PRIMARY KEY NOT NULL,
[EmployeeId] INT NOT NULL,
CONSTRAINT FE_Sellers FOREIGN KEY (EmployeeId) REFERENCES Employee(Id)
);
CREATE TABLE Network(
    [Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [Adress] VARCHAR(MAX)  NOT NULL,
    [Phone] INT NOT NULL
);
GO
CREATE TABLE EmployeeArchive(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Name] VARCHAR(MAX) NOT NULL,
[Surname] VARCHAR(MAX) NOT NULL,
[ReleaseDate] DATETIME NOT NULL,
[Salary] MONEY NOT NULL
);
GO
CREATE TABLE Goods(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Name] VARCHAR(MAX) NOT NULL,
[Trademark] VARCHAR(MAX) NOT NULL,
[Category] VARCHAR(50) NOT NULL,
[Amount] INT NOT NULL,
[Price] MONEY NOT NULL,
[Code] INT NOT NULL
);
GO
CREATE TABLE Storage(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[GoodsId] INT NOT NULL,
[DeliveryDate] DATETIME NOT NULL,
[AmountStorage] INT NOT NULL,
CONSTRAINT FK_Storage FOREIGN KEY (GoodsId) REFERENCES Goods(Id)
);
GO
CREATE TABLE OrderGoods(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[GoodsId] INT NOT NULL,
[NetworkId] INT NOT NULL,
[Amount] INT NOT NULL,
CONSTRAINT FG_Order FOREIGN KEY (GoodsId) REFERENCES Goods(Id),
CONSTRAINT FN_Order FOREIGN KEY (NetworkId) REFERENCES Network(Id),
);
GO
CREATE TABLE GoodsInShops(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[NetworkId] INT NOT NULL,
[GoodsId] INT NOT NULL,
[Amount] INT NOT NULL,
CONSTRAINT FG_GoodsInShops FOREIGN KEY (GoodsId) REFERENCES Goods(Id),
CONSTRAINT FN_GoodsInShops FOREIGN KEY (NetworkId) REFERENCES Network(Id),
);